# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OptimusPrime' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings! 	
  
   #    网络
    pod 'AFNetworking', '~> 3.2.1'
    #    AutoLayout
    pod 'Masonry', '~> 1.1.0'
    #    图片缓存
    pod 'SDWebImage', '~> 5.0.4'
    
    #    字典转模型
    pod 'YYModel', '~> 1.0.4'
    #    缓存框架
    pod 'YYCache', '~> 1.0.4'
    
    #    pod 'YYCategories', '~> 1.0.4'
    
    pod 'ReactiveObjC', '~> 3.1.1'



  target 'OptimusPrimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
